# Generated by Django 5.2.3 on 2025-06-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('courses', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('payments', models.CharField(blank=True, max_length=100)),
                ('goal', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
