# Generated by Django 5.2.3 on 2025-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='accounts.course'),
        ),
    ]
