# Generated by Django 5.2.3 on 2025-06-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_remove_userprofile_goal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='courses',
            new_name='enrolled_courses',
        ),
    ]
